tasks: 
- name: Start Workshop
  init: |
   curl -o .env https://talkin-ship-workshop.s3.us-east-2.amazonaws.com/target.env
   npm install
  command: npm run dev

ports: 
  - port: 3000
    onOpen: open-preview
    name: Launch Airways
    description: Launch Airways preview